services:
  app:
    # image: eyesman/nodejs2024q3-service-app
    container_name: nodejs2024q3-service-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    restart: always
    networks:
      - home-library
    command: npm run start:dev

  db:
    # image: eyesman/nodejs2024q3-service-db
    container_name: nodejs2024q3-service-db
    build:
      dockerfile: Dockerfile.db
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${POSTGRES_INTERNAL_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/logs
    restart: always
    networks:
      - home-library

volumes:
  data:
  logs:

networks:
  home-library:
    driver: bridge